import {
  createHttpFactory,
  HttpMethod,
  SpectatorHttp,
} from '@ngneat/spectator/jest';

import { MaterialCustomerService } from './material-customer.service';

describe('MaterialCustomerService', () => {
  let spectator: SpectatorHttp<MaterialCustomerService>;
  const createHttp = createHttpFactory(MaterialCustomerService);

  beforeEach(() => {
    spectator = createHttp();
  });

  afterEach(() => {
    spectator.controller.verify();
  });

  it('should return total materials count of customer', () => {
    const mockResponse = { rowCount: 5 };
    const customerNumber = '123';

    spectator.service
      .getTotalMaterialsCountOfCustomer(customerNumber)
      .subscribe((response) => {
        expect(response).toEqual(mockResponse.rowCount);
      });

    const req = spectator.expectOne('api/material-customer', HttpMethod.POST);
    req.flush(mockResponse);
  });

  it('should return an empty observable when customer number is not provided', () => {
    spectator.service
      .getTotalMaterialsCountOfCustomer()
      .subscribe((response) => {
        expect(response).toBeUndefined();
      });
  });

  it('should return criteria data', () => {
    const mockResponse = { field1: 'value1', field2: 'value2' };

    spectator.service.getCriteriaData().subscribe((response) => {
      expect(response).toEqual(mockResponse);
    });

    const req = spectator.expectOne(
      'api/material-customer/criteria-fields',
      HttpMethod.GET
    );
    req.flush(mockResponse);
  });

  it('should return material customer data', () => {
    const mockResponse = {
      rows: [{ materialNumber: '123', materialDescription: 'description' }],
      rowCount: 1,
    };
    const selectedIds = ['123'];

    spectator.service
      .getMaterialCustomerData(selectedIds)
      .subscribe((response) => {
        expect(response).toEqual(mockResponse);
      });

    const req = spectator.expectOne(
      'api/material-customer/materials',
      HttpMethod.POST
    );
    req.flush(mockResponse);
  });

  // TODO add test for error handling and test with logic. This test are generated by copilot
});
