# Specify the number of open pull requests allowed

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 5
    labels:
      - 'type:dep-update'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@nrwl/*'
      - dependency-name: '@ngrx/*'
      - dependency-name: '@storybook/*'
      - dependency-name: '@ag-grid-*'
      - dependency-name: '@angular-eslint/*'
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: 'eslint'
      - dependency-name: 'eslint-*'
