# Specify the number of open pull requests allowed

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 10
    labels:
      - 'type:dep-update'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      angular:
        patterns:
          - '@angular/*'
          - 'ng-packagr'
      nx:
        patterns:
          - '@nrwl/*'
          - '@nx/*'
      ngrx:
        patterns:
          - '@ngrx/*'
      storybook:
        patterns:
          - '@storybook/*'
      ag-grid:
        patterns:
          - '@ag-grid-*'
      angular-eslint:
        patterns:
          - '@angular-eslint/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
