/* dialog pages */
export const RSY_PAGE_BEARING_TYPE = 'RSY_PAGE_BEARING_TYPE';
export const PAGE_MOUNTING_MANAGER_SEAT = 'PAGE_MOUNTING_MANAGER_SEAT';

/* dialog members */
export const RSY_BEARING_TYPE = 'RSY_BEARING_TYPE';
export const RSY_BEARING_SERIES = 'RSY_BEARING_SERIES';
export const RSY_BEARING = 'RSY_BEARING';
export const IDCO_DESIGNATION = 'IDCO_DESIGNATION';
export const IDMM_SHAFT_MATERIAL = 'IDMM_SHAFT_MATERIAL';
export const IDMM_BEARING_SEAT = 'IDMM_BEARING_SEAT';
export const IDMM_HYDRAULIC_NUT_TYPE = 'IDMM_HYDRAULIC_NUT_TYPE';
export const IDMM_INNER_RING_EXPANSION = 'IDMM_INNER_RING_EXPANSION';
export const IDMM_RADIAL_CLEARANCE_REDUCTION =
  'IDMM_RADIAL_CLEARANCE_REDUCTION';
export const IDMM_MODULUS_OF_ELASTICITY = 'IDMM_MODULUS_OF_ELASTICITY';
export const IDMM_POISSON_RATIO = 'IDMM_POISSON_RATIO';

/* runtime tables */
export const TBL_BEARING_PREFLIGHT = 'TBL_BEARING_PREFLIGHT';
export const TBL_SHAFT_MATERIAL = 'TBL_SHAFT_MATERIAL';
