/* eslint-disable max-lines */

import { ColDef } from 'ag-grid-community';

import {
  BUSINESS_PARTNER_ID,
  CALCULATION_METHOD_VERIFIED_BY_3RD_PARTY,
  CATEGORY,
  CATEGORY_TEXT,
  CROSS_SECTORAL_STANDARDS_USED,
  CUSTOMER_CALCULATION_METHOD_APPLIED,
  DATA_COMMENT,
  DATA_DATE,
  DQR_PRIMARY,
  DQR_SECONDARY,
  EMISSION_FACTOR_KG,
  EMISSION_FACTOR_PC,
  FOSSIL_ENERGY_SHARE,
  INCOTERMS,
  LINK_TO_3RD_PARTY_VERIFICATION_PROOF,
  LINK_TO_CUSTOMER_CALCULATION_METHOD,
  MATERIAL_DESCRIPTION,
  MATERIAL_GROUP,
  MATERIAL_GROUP_OF_RAW_MATERIAL,
  MATERIAL_GROUP_TEXT,
  MATERIAL_NUMBER,
  MATERIAL_UTILIZATION_FACTOR,
  MATURITY,
  NET_WEIGHT,
  NUCLEAR_ENERGY_SHARE,
  ONLY_RENEWABLE_ELECTRICITY,
  OWNER,
  PCF_LOGISTICS,
  PCF_VERIFIED_BY_3RD_PARTY,
  PLANT,
  PLANT_TEXT,
  PRIMARY_DATA_SHARE,
  PROCESS_SURCHARGE,
  RAW_MATERIAL_EMISSION_FACTOR,
  RAW_MATERIAL_MANUFACTURER,
  RECYCLED_MATERIAL_SHARE,
  RENEWABLE_ENERGY_SHARE,
  SECONDARY_DATA_SOURCES,
  SECONDARY_MATERIAL_SHARE,
  SERVICE_INPUT_GROSS_WEIGHT,
  STOFF_ID,
  SUPPLIER_COUNTRY,
  SUPPLIER_ID,
  SUPPLIER_ID_TEXT,
  SUPPLIER_LOCATION,
  SUPPLIER_REGION,
  VALID_FROM,
  VALID_UNTIL,
  WEIGHT_DATA_SOURCE,
} from '@mac/feature/materials-supplier-database/constants';
import {
  DISTINCT_FILTER_PARAMS,
  NUMBER_FILTER_PARAMS,
  TEXT_FILTER_PARAMS,
} from '@mac/msd/main-table/table-config';

import { PcfMaturityCo2CellRendererComponent } from '../../../pcf-maturity-co2-cell-renderer/pcf-maturity-co2-cell-renderer.component';
import { UrlCellRendererComponent } from '../../../url-cell-renderer/url-cell-renderer.component';
import {
  BOOLEAN_VALUE_FORMATTER,
  EMISSION_FACTORS_FORMATTER,
  MATURITY_FORMATTER,
  PERCENT_FORMATTER,
  SAP_MATERIALS_DATE_FORMATTER,
} from '../../helpers';
import { HISTORY_COLUMN_DEFINITION } from '../base';

export const SAP_MATERIALS_COLUMN_DEFINITIONS: ColDef[] = [
  HISTORY_COLUMN_DEFINITION,
  {
    field: MATERIAL_NUMBER,
    headerName: MATERIAL_NUMBER,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    headerTooltip: MATERIAL_NUMBER,
  },
  {
    field: MATERIAL_DESCRIPTION,
    headerName: MATERIAL_DESCRIPTION,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
  },
  {
    field: RECYCLED_MATERIAL_SHARE,
    headerName: RECYCLED_MATERIAL_SHARE,
    filter: 'agNumberColumnFilter',
    valueFormatter: PERCENT_FORMATTER,
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: 'percent',
    hide: true,
  },
  {
    field: SECONDARY_MATERIAL_SHARE,
    headerName: SECONDARY_MATERIAL_SHARE,
    filter: 'agNumberColumnFilter',
    valueFormatter: PERCENT_FORMATTER,
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: 'percent',
    hide: true,
  },
  {
    field: CATEGORY,
    headerName: CATEGORY,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    tooltipField: CATEGORY_TEXT,
    tooltipComponentParams: {
      translate: false,
    },
  },
  {
    field: MATERIAL_GROUP,
    headerName: MATERIAL_GROUP,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    tooltipField: MATERIAL_GROUP_TEXT,
    tooltipComponentParams: {
      translate: false,
    },
  },
  {
    field: DATA_COMMENT,
    headerName: DATA_COMMENT,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
  },
  {
    field: BUSINESS_PARTNER_ID,
    headerName: BUSINESS_PARTNER_ID,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    tooltipField: SUPPLIER_ID_TEXT,
    tooltipComponentParams: {
      translate: false,
    },
  },
  {
    field: SUPPLIER_ID,
    headerName: SUPPLIER_ID,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    tooltipField: SUPPLIER_ID_TEXT,
    tooltipComponentParams: {
      translate: false,
    },
  },
  {
    field: RAW_MATERIAL_MANUFACTURER,
    headerName: RAW_MATERIAL_MANUFACTURER,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    hide: true,
  },
  {
    field: INCOTERMS,
    headerName: INCOTERMS,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    hide: true,
    headerTooltip: INCOTERMS,
  },
  {
    field: SUPPLIER_LOCATION,
    headerName: SUPPLIER_LOCATION,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    headerTooltip: SUPPLIER_LOCATION,
    hide: true,
  },
  {
    field: PLANT,
    headerName: PLANT,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    tooltipField: PLANT_TEXT,
    tooltipComponentParams: {
      translate: false,
    },
    headerTooltip: PLANT,
  },
  {
    field: SUPPLIER_COUNTRY,
    headerName: SUPPLIER_COUNTRY,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    headerTooltip: SUPPLIER_COUNTRY,
  },
  {
    field: SUPPLIER_REGION,
    headerName: SUPPLIER_REGION,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    headerTooltip: SUPPLIER_REGION,
  },
  {
    field: FOSSIL_ENERGY_SHARE,
    headerName: FOSSIL_ENERGY_SHARE,
    filter: 'agNumberColumnFilter',
    valueFormatter: PERCENT_FORMATTER,
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
    headerTooltip: 'productionLocationsShare',
  },
  {
    field: NUCLEAR_ENERGY_SHARE,
    headerName: NUCLEAR_ENERGY_SHARE,
    filter: 'agNumberColumnFilter',
    valueFormatter: PERCENT_FORMATTER,
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
    headerTooltip: 'productionLocationsShare',
  },
  {
    field: RENEWABLE_ENERGY_SHARE,
    headerName: RENEWABLE_ENERGY_SHARE,
    filter: 'agNumberColumnFilter',
    valueFormatter: PERCENT_FORMATTER,
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
    headerTooltip: 'productionLocationsShare',
  },
  {
    field: ONLY_RENEWABLE_ELECTRICITY,
    headerName: ONLY_RENEWABLE_ELECTRICITY,
    valueFormatter: BOOLEAN_VALUE_FORMATTER,
    filter: 'agSetColumnFilter',
    filterParams: {
      ...DISTINCT_FILTER_PARAMS,
      valueFormatter: BOOLEAN_VALUE_FORMATTER,
    },
    headerTooltip: 'boolean',
    hide: true,
  },
  {
    field: VALID_FROM,
    headerName: VALID_FROM,
    filter: 'agDateColumnFilter',
    valueFormatter: SAP_MATERIALS_DATE_FORMATTER,
    headerTooltip: 'date',
    hide: true,
  },
  {
    field: VALID_UNTIL,
    headerName: VALID_UNTIL,
    filter: 'agDateColumnFilter',
    valueFormatter: SAP_MATERIALS_DATE_FORMATTER,
    headerTooltip: 'date',
    hide: true,
  },
  {
    field: PRIMARY_DATA_SHARE,
    headerName: PRIMARY_DATA_SHARE,
    filter: 'agNumberColumnFilter',
    valueFormatter: PERCENT_FORMATTER,
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
    headerTooltip: 'percent',
  },
  {
    field: DQR_PRIMARY,
    headerName: DQR_PRIMARY,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
  },
  {
    field: DQR_SECONDARY,
    headerName: DQR_SECONDARY,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
  },
  {
    field: SECONDARY_DATA_SOURCES,
    headerName: SECONDARY_DATA_SOURCES,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    hide: true,
  },
  {
    field: CROSS_SECTORAL_STANDARDS_USED,
    headerName: CROSS_SECTORAL_STANDARDS_USED,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    hide: true,
  },
  {
    field: CUSTOMER_CALCULATION_METHOD_APPLIED,
    headerName: CUSTOMER_CALCULATION_METHOD_APPLIED,
    valueFormatter: BOOLEAN_VALUE_FORMATTER,
    filter: 'agSetColumnFilter',
    filterParams: {
      ...DISTINCT_FILTER_PARAMS,
      valueFormatter: BOOLEAN_VALUE_FORMATTER,
    },
    headerTooltip: 'boolean',
    hide: true,
  },
  {
    field: LINK_TO_CUSTOMER_CALCULATION_METHOD,
    headerName: LINK_TO_CUSTOMER_CALCULATION_METHOD,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    cellRenderer: UrlCellRendererComponent,
    headerTooltip: 'url',
    hide: true,
  },
  {
    field: CALCULATION_METHOD_VERIFIED_BY_3RD_PARTY,
    headerName: CALCULATION_METHOD_VERIFIED_BY_3RD_PARTY,
    valueFormatter: BOOLEAN_VALUE_FORMATTER,
    filter: 'agSetColumnFilter',
    filterParams: {
      ...DISTINCT_FILTER_PARAMS,
      valueFormatter: BOOLEAN_VALUE_FORMATTER,
    },
    headerTooltip: 'boolean',
    hide: true,
  },
  {
    field: LINK_TO_3RD_PARTY_VERIFICATION_PROOF,
    headerName: LINK_TO_3RD_PARTY_VERIFICATION_PROOF,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    cellRenderer: UrlCellRendererComponent,
    headerTooltip: 'url',
    hide: true,
  },
  {
    field: PCF_VERIFIED_BY_3RD_PARTY,
    headerName: PCF_VERIFIED_BY_3RD_PARTY,
    valueFormatter: BOOLEAN_VALUE_FORMATTER,
    filter: 'agSetColumnFilter',
    filterParams: {
      ...DISTINCT_FILTER_PARAMS,
      valueFormatter: BOOLEAN_VALUE_FORMATTER,
    },
    headerTooltip: 'boolean',
    hide: true,
  },
  {
    field: EMISSION_FACTOR_KG,
    headerName: EMISSION_FACTOR_KG,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    cellRenderer: PcfMaturityCo2CellRendererComponent,
    valueFormatter: EMISSION_FACTORS_FORMATTER,
    headerTooltip: EMISSION_FACTOR_KG,
  },
  {
    field: EMISSION_FACTOR_PC,
    headerName: EMISSION_FACTOR_PC,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    cellRenderer: PcfMaturityCo2CellRendererComponent,
    valueFormatter: EMISSION_FACTORS_FORMATTER,
    headerTooltip: EMISSION_FACTOR_PC,
  },
  {
    field: PCF_LOGISTICS,
    headerName: PCF_LOGISTICS,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: PCF_LOGISTICS,
    hide: true,
  },
  {
    field: SERVICE_INPUT_GROSS_WEIGHT,
    headerName: SERVICE_INPUT_GROSS_WEIGHT,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    hide: true,
  },
  {
    field: NET_WEIGHT,
    headerName: NET_WEIGHT,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: NET_WEIGHT,
    hide: true,
  },
  {
    field: WEIGHT_DATA_SOURCE,
    headerName: WEIGHT_DATA_SOURCE,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    headerTooltip: WEIGHT_DATA_SOURCE,
    hide: true,
  },
  {
    field: MATERIAL_UTILIZATION_FACTOR,
    headerName: MATERIAL_UTILIZATION_FACTOR,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: MATERIAL_UTILIZATION_FACTOR,
    hide: true,
  },
  {
    field: MATERIAL_GROUP_OF_RAW_MATERIAL,
    headerName: MATERIAL_GROUP_OF_RAW_MATERIAL,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
    headerTooltip: MATERIAL_GROUP_OF_RAW_MATERIAL,
    hide: true,
  },
  {
    field: RAW_MATERIAL_EMISSION_FACTOR,
    headerName: RAW_MATERIAL_EMISSION_FACTOR,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: 'co2perkg',
    hide: true,
  },
  {
    field: PROCESS_SURCHARGE,
    headerName: PROCESS_SURCHARGE,
    filter: 'agNumberColumnFilter',
    filterParams: NUMBER_FILTER_PARAMS,
    headerTooltip: 'co2perkg',
    hide: true,
  },
  {
    field: STOFF_ID,
    headerName: STOFF_ID,
    filter: 'agTextColumnFilter',
    filterParams: TEXT_FILTER_PARAMS,
    hide: true,
  },
  {
    field: DATA_DATE,
    headerName: DATA_DATE,
    filter: false,
    valueFormatter: SAP_MATERIALS_DATE_FORMATTER,
  },

  {
    field: MATURITY,
    headerName: MATURITY,
    filter: 'agSetColumnFilter',
    filterParams: {
      ...DISTINCT_FILTER_PARAMS,
      valueFormatter: MATURITY_FORMATTER,
      suppressSorting: true,
    },
    valueFormatter: MATURITY_FORMATTER,
  },
  {
    field: OWNER,
    headerName: OWNER,
    filter: 'agSetColumnFilter',
    filterParams: DISTINCT_FILTER_PARAMS,
  },
];
