export enum QuotationStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
  REJECTED = 'REJECTED',
  TO_BE_APPROVED = 'TO_BE_APPROVED',
  IN_APPROVAL = 'IN_APPROVAL',
  APPROVED = 'APPROVED',
}
