import { QuickFilter } from '@mac/feature/materials-supplier-database/models';
import {
  CO2_PER_TON,
  LAST_MODIFIED,
  MANUFACTURER_SUPPLIER_COUNTRY,
  MANUFACTURER_SUPPLIER_NAME,
  MANUFACTURER_SUPPLIER_PLANT,
  MANUFACTURER_SUPPLIER_REGION,
  MATERIAL_STANDARD_MATERIAL_NAME,
  MATERIAL_STANDARD_STANDARD_DOCUMENT,
  PRODUCT_CATEGORY,
  RELEASE_DATE,
  RELEASE_RESTRICTIONS,
} from '@mac/msd/constants';

export const POLYMER_STATIC_QUICKFILTERS: QuickFilter[] = [
  {
    title: 'All view',
    filter: {},
    columns: [
      MATERIAL_STANDARD_MATERIAL_NAME,
      MATERIAL_STANDARD_STANDARD_DOCUMENT,
      MANUFACTURER_SUPPLIER_NAME,
      MANUFACTURER_SUPPLIER_PLANT,
      MANUFACTURER_SUPPLIER_COUNTRY,
      MANUFACTURER_SUPPLIER_REGION,
      RELEASE_RESTRICTIONS,
      PRODUCT_CATEGORY,
      CO2_PER_TON,
      LAST_MODIFIED,
      RELEASE_DATE,
    ],
  },
];
