import { PlanningView } from '../../../feature/demand-validation/planning-view';
import {
  ChartUnitMode,
  ForecastChartData,
} from '../../../feature/forecast-chart/model';

export const previewDataMonthly: ForecastChartData = {
  currency: 'EUR',
  chartUnitMode: ChartUnitMode.CURRENCY,
  planningView: PlanningView.REQUESTED,
  chartEntries: [
    {
      yearMonth: '2022-01-01',
      orders: 0,
      deliveries: 6000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2022-02-01',
      orders: 0,
      deliveries: 4000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2022-03-01',
      orders: 0,
      deliveries: 5000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2022-04-01',
      orders: 200,
      deliveries: 8000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2022-05-01',
      orders: 400,
      deliveries: 0,
      onTopOrder: 4000,
      onTopCapacityForecast: 1000,
      opportunities: 500,
      salesAmbition: 300,
      rollingSalesForecast: 4000,
    },
    {
      yearMonth: '2022-06-01',
      orders: 200,
      deliveries: 0,
      onTopOrder: 4500,
      onTopCapacityForecast: 1000,
      opportunities: 400,
      salesAmbition: 200,
      rollingSalesForecast: 4500,
    },
    {
      yearMonth: '2022-07-01',
      orders: 0,
      deliveries: 0,
      onTopOrder: 6000,
      onTopCapacityForecast: 1000,
      opportunities: 600,
      salesAmbition: 300,
      rollingSalesForecast: 6000,
    },
    {
      yearMonth: '2022-08-01',
      orders: 0,
      deliveries: 0,
      onTopOrder: 2500,
      onTopCapacityForecast: 2500,
      opportunities: 100,
      salesAmbition: 100,
      rollingSalesForecast: 3000,
    },
    {
      yearMonth: '2022-09-01',
      orders: 0,
      deliveries: 0,
      onTopOrder: 2500,
      onTopCapacityForecast: 2500,
      opportunities: 100,
      salesAmbition: 100,
      rollingSalesForecast: 3000,
    },
  ],
};

export const previewDataYearly: ForecastChartData = {
  currency: 'EUR',
  chartUnitMode: ChartUnitMode.CURRENCY,
  planningView: PlanningView.REQUESTED,
  chartEntries: [
    {
      yearMonth: '2022-01-01',
      orders: 0,
      deliveries: 3000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2022-02-01',
      orders: 0,
      deliveries: 4000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2023-03-01',
      orders: 0,
      deliveries: 5000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2024-01-01',
      orders: 200,
      deliveries: 8000,
      onTopOrder: 0,
      onTopCapacityForecast: 0,
      opportunities: 0,
      salesAmbition: 0,
      rollingSalesForecast: null,
    },
    {
      yearMonth: '2025-01-01',
      orders: 500,
      deliveries: 0,
      onTopOrder: 4000,
      onTopCapacityForecast: 1000,
      opportunities: 500,
      salesAmbition: 500,
      rollingSalesForecast: 6500,
    },
    {
      yearMonth: '2026-01-01',
      orders: 100,
      deliveries: 0,
      onTopOrder: 3500,
      onTopCapacityForecast: 1000,
      opportunities: 500,
      salesAmbition: 400,
      rollingSalesForecast: 5500,
    },
    {
      yearMonth: '2027-01-01',
      orders: 0,
      deliveries: 0,
      onTopOrder: 6000,
      onTopCapacityForecast: 1000,
      opportunities: 700,
      salesAmbition: 300,
      rollingSalesForecast: 8000,
    },
  ],
};
