import { addMonths, format, getYear, subMonths } from 'date-fns';

import { PlanningView } from '../../../feature/demand-validation/planning-view';
import {
  ChartUnitMode,
  ForecastChartData,
} from '../../../feature/forecast-chart/model';

export function previewDataMonthly(): ForecastChartData {
  const currentDate = new Date();

  return {
    currency: 'EUR',
    chartUnitMode: ChartUnitMode.CURRENCY,
    planningView: PlanningView.REQUESTED,
    chartEntries: [
      {
        yearMonth: format(subMonths(currentDate, 3), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 6000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        opportunities: 0,
        salesAmbition: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(subMonths(currentDate, 2), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 4000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        salesAmbition: 0,
        opportunities: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(subMonths(currentDate, 1), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 5000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        salesAmbition: 0,
        opportunities: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(currentDate, 'yyyy-MM-dd'),
        orders: 200,
        deliveries: 4000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        salesAmbition: 0,
        opportunities: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(addMonths(currentDate, 1), 'yyyy-MM-dd'),
        orders: 400,
        deliveries: 0,
        onTopOrder: 4000,
        onTopCapacityForecast: 1000,
        salesAmbition: 300,
        opportunities: 500,
        salesPlan: 6200,
        bwDelta: 620,
      },
      {
        yearMonth: format(addMonths(currentDate, 2), 'yyyy-MM-dd'),
        orders: 200,
        deliveries: 0,
        onTopOrder: 4500,
        onTopCapacityForecast: 1000,
        salesAmbition: 200,
        opportunities: 400,
        salesPlan: 6300,
        bwDelta: 630,
      },
      {
        yearMonth: format(addMonths(currentDate, 3), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 6000,
        onTopCapacityForecast: 1000,
        salesAmbition: 300,
        opportunities: 600,
        salesPlan: 7900,
        bwDelta: 790,
      },
      {
        yearMonth: format(addMonths(currentDate, 4), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 2500,
        onTopCapacityForecast: 2000,
        salesAmbition: 600,
        opportunities: 100,
        salesPlan: 5200,
        bwDelta: 520,
      },
      {
        yearMonth: format(addMonths(currentDate, 5), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 2500,
        onTopCapacityForecast: 2000,
        salesAmbition: 600,
        opportunities: 600,
        salesPlan: 5700,
        bwDelta: 570,
      },
      {
        yearMonth: format(addMonths(currentDate, 6), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 2500,
        onTopCapacityForecast: 3000,
        salesAmbition: 600,
        opportunities: 500,
        salesPlan: 6600,
        bwDelta: 660,
      },
      {
        yearMonth: format(addMonths(currentDate, 7), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 2500,
        onTopCapacityForecast: 2000,
        salesAmbition: 900,
        opportunities: 800,
        salesPlan: 6200,
        bwDelta: 620,
      },
      {
        yearMonth: format(addMonths(currentDate, 8), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 2500,
        onTopCapacityForecast: 2500,
        salesAmbition: 300,
        opportunities: 800,
        salesPlan: 6100,
        bwDelta: 610,
      },
    ],
  };
}

export function previewDataYearly(): ForecastChartData {
  const currentYear = getYear(new Date());

  return {
    currency: 'EUR',
    chartUnitMode: ChartUnitMode.CURRENCY,
    planningView: PlanningView.REQUESTED,
    chartEntries: [
      {
        yearMonth: format(new Date(currentYear - 2, 0, 1), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 4000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        salesAmbition: 0,
        opportunities: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(new Date(currentYear - 1, 0, 1), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 5000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        salesAmbition: 0,
        opportunities: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(new Date(currentYear, 0, 1), 'yyyy-MM-dd'),
        orders: 200,
        deliveries: 8000,
        onTopOrder: 0,
        onTopCapacityForecast: 0,
        salesAmbition: 0,
        opportunities: 0,
        salesPlan: null,
        bwDelta: 0,
      },
      {
        yearMonth: format(new Date(currentYear + 1, 0, 1), 'yyyy-MM-dd'),
        orders: 500,
        deliveries: 0,
        onTopOrder: 4000,
        onTopCapacityForecast: 1000,
        salesAmbition: 500,
        opportunities: 500,
        salesPlan: 6500,
        bwDelta: 650,
      },
      {
        yearMonth: format(new Date(currentYear + 2, 0, 1), 'yyyy-MM-dd'),
        orders: 100,
        deliveries: 0,
        onTopOrder: 3500,
        onTopCapacityForecast: 1000,
        salesAmbition: 400,
        opportunities: 500,
        salesPlan: 5500,
        bwDelta: 550,
      },
      {
        yearMonth: format(new Date(currentYear + 3, 0, 1), 'yyyy-MM-dd'),
        orders: 0,
        deliveries: 0,
        onTopOrder: 6000,
        onTopCapacityForecast: 1000,
        salesAmbition: 300,
        opportunities: 700,
        salesPlan: 8000,
        bwDelta: 800,
      },
    ],
  };
}
