name: 'Docs (Confluence, Workspace, Storybook)'
description: Report an issue in Confluence/Workspace/Storybook documentation

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Please provide the steps to reproduce the issue

  - type: textarea
    id: expected-vs-actual-behavior
    attributes:
      label: Please provide the expected behavior vs the actual behavior you encountered

  - type: textarea
    id: screenshot
    attributes:
      label: Please provide a screenshot if possible

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true
