name: 'Refactoring Request'
description: Suggest something that needs to be refactored in the frontend-schaeffler Monorepository and its packages

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which projects are relevant/releated to the refactoring request?
      options:
        - General / Workspace
        - Build Pipeline
        - Shared User Interface Library
        - Shared Utility Library
        - Unknown / other
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true

  - type: textarea
    id: additional-hints
    attributes:
      label: Additional Hints
    validations:
      required: false
