export enum PriceSource {
  GQ = 'GQ',
  SAP_STANDARD = 'SAP_STANDARD',
  SAP_SPECIAL = 'SAP_SPECIAL',
  CAP_PRICE = 'CAP_PRICE',
  STRATEGIC = 'STRATEGIC',
  MANUAL = 'MANUAL',
  TARGET_PRICE = 'TARGET_PRICE',
}
