import {
  IDCO_DESIGNATION,
  IDMM_BEARING_SEAT,
  IDMM_CLEARANCE_REDUCTION_INPUT,
  IDMM_HYDRAULIC_NUT_TYPE,
  IDMM_INNER_RING_EXPANSION,
  IDMM_INNER_SHAFT_DIAMETER,
  IDMM_MEASSURING_METHOD,
  IDMM_MODULUS_OF_ELASTICITY,
  IDMM_MOUNTING_METHOD,
  IDMM_NUMBER_OF_PREVIOUS_MOUNTINGS,
  IDMM_POISSON_RATIO,
  IDMM_RADIAL_CLEARANCE_REDUCTION,
  IDMM_SHAFT_MATERIAL,
} from '@mm/shared/constants/dialog-constant';

export interface CalculationRequestPayload {
  [IDCO_DESIGNATION]: string;
  [IDMM_BEARING_SEAT]: string;
  [IDMM_CLEARANCE_REDUCTION_INPUT]: string;
  [IDMM_HYDRAULIC_NUT_TYPE]: string;
  [IDMM_INNER_RING_EXPANSION]: string | number;
  [IDMM_INNER_SHAFT_DIAMETER]: string | number;
  [IDMM_MEASSURING_METHOD]: string;
  [IDMM_MODULUS_OF_ELASTICITY]: string | number;
  [IDMM_MOUNTING_METHOD]: string;
  [IDMM_NUMBER_OF_PREVIOUS_MOUNTINGS]: string;
  [IDMM_POISSON_RATIO]: string | number;
  [IDMM_RADIAL_CLEARANCE_REDUCTION]: string | number;
  [IDMM_SHAFT_MATERIAL]: string;
}
