// classic
export interface BomItemClassic {
  level: number;
  currency: string;
  plant: string;
  cavity: number;
  lotsize: number;
  materialDesignation: string;
  totalPricePerPc: number;
  materialNumber: string;
  procurementType: string;
  activityType: string;
  setupTime: number;
  cycleTime: number;
  toolingFactor: number;
  quantityPerParent: number;
  unitOfMeasure: string;
  costCenter: string;
  currencyForeign: string;
  parentLotsize: number;
  parentMaterialNumber: string;
  parentPlant: string;
  bomCostingDate: string;
  bomCostingNumber: string;
  bomCostingVersion: string;
  bomCostingType: string;
  bomEnteredManually: string;
  bomReferenceObject: string;
  bomValuationVariant: string;
  rowId: number;
  predecessorsInTree: string[];
  costShareOfParent?: number;
}
