import { PcmCalculation } from './pcm-calculation.model';

export interface ReferenceType {
  id: string;
  materialNumber: string;
  plant: string;
  budgetQuantityCurrentYear: number;
  budgetQuantitySoco: number;
  currency: string;
  gpcDate: string;
  gpcLatestYear: number;
  height: number;
  length: number;
  width: number;
  unitOfDimension: string;
  materialDesignation: string;
  materialShortDescription: string;
  procurementType: string;
  productLine: string;
  purchasePriceValidFrom: string;
  purchasePriceValidUntil: string;
  puUm: string;
  specialProcurement: string;
  sqvDate: string;
  supplier: string;
  volumeCubic: number;
  volumeUnit: string;
  weight: number;
  weightUnit: string;
  inquiryType: string;
  pcmCalculations: PcmCalculation[];
  quotationNumber: string;
  netSales: number[];
  averagePrices: number[];
  actualQuantities: number[];
  plannedQuantities: number[];
  customerGroups: string[];
  customers: string[];
  salesOrganizations: string[];
  productDescription: string;
  sqvSapLatestMonth: number;
  isPcmRow: boolean;
}
