import { HttpClient } from '@angular/common/http';

import { of } from 'rxjs';

import { MockProvider } from 'ng-mocks';

import { GridTooltipComponent } from '../../../../shared/components/ag-grid/grid-tooltip/grid-tooltip.component';
import { Stub } from '../../../../shared/test/stub.class';
import { AlertRulesColumnSettingsService } from './alert-rules-column-settings.service';

describe('AlertRulesColumnSettingsService', () => {
  let service: AlertRulesColumnSettingsService<any, any>;
  beforeEach(() => {
    service = Stub.get<AlertRulesColumnSettingsService<any, any>>({
      component: AlertRulesColumnSettingsService,
      providers: [
        // we need it here, can't be removed!
        MockProvider(
          HttpClient,
          { get: () => of([]), post: () => of({}) },
          'useValue'
        ),
      ],
    });
  });

  it('should create', () => {
    expect(service).toBeTruthy();
  });

  it('sets initial data', () => {
    expect(service['columnSettings'].getValue()).toEqual([
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'region',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 0,
        sort: null,
        sortable: true,
        title: 'material_customer.column.region',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'salesArea',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 1,
        sort: null,
        sortable: true,
        title: 'material_customer.column.salesArea',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'salesOrg',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 2,
        sort: null,
        sortable: true,
        title: 'material_customer.column.salesOrg',
        visible: true,
      },
      {
        alwaysVisible: true,
        cellRenderer: undefined,
        colId: 'customerNumber',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 3,
        sort: null,
        sortable: true,
        title: 'material_customer.column.customerNumber',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'customerName',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 4,
        sort: null,
        sortable: true,
        title: 'material_customer.column.customerName',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'materialNumber',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 5,
        sort: null,
        sortable: true,
        title: 'material_customer.column.materialNumber',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'materialDescription',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 6,
        sort: null,
        sortable: true,
        title: 'material_customer.column.materialDescription',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'materialClassification',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 7,
        sort: null,
        sortable: true,
        title: 'material_customer.column.materialClassification',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'sectorManagement',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 8,
        sort: null,
        sortable: true,
        title: 'material_customer.column.sectorManagement',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'productionLine',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 9,
        sort: null,
        sortable: true,
        title: 'material_customer.column.productionLine',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'productLine',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 10,
        sort: null,
        sortable: true,
        title: 'material_customer.column.productLine',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'gkamNumber',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 11,
        sort: null,
        sortable: true,
        title: 'material_customer.column.gkamNumber',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'gkamName',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 12,
        sort: null,
        sortable: true,
        title: 'material_customer.column.gkamName',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'demandPlanner',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 13,
        sort: null,
        sortable: true,
        title: 'material_customer.column.demandPlanner',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'alertComment',
        filter: undefined,
        filterParams: undefined,
        maxWidth: 375,
        order: 14,
        sort: null,
        sortable: false,
        title: 'alert_rules.edit_modal.label.remark',
        tooltipComponent: GridTooltipComponent,
        tooltipComponentParams: {
          lineBreaks: true,
          textLeft: true,
          wide: true,
        },
        tooltipField: 'alertComment',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'threshold1',
        filter: 'agNumberColumnFilter',
        filterParams: undefined,
        order: 15,
        sort: null,
        sortable: true,
        title: 'rules.threshold1',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'threshold1Description',
        filter: undefined,
        filterParams: undefined,
        order: 16,
        sort: null,
        sortable: false,
        title: 'rules.threshold1Description',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'threshold2',
        filter: 'agNumberColumnFilter',
        filterParams: undefined,
        order: 17,
        sort: null,
        sortable: true,
        title: 'rules.threshold2',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'threshold2Description',
        filter: undefined,
        filterParams: undefined,
        order: 18,
        sort: null,
        sortable: false,
        title: 'rules.threshold2Description',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'threshold3',
        filter: 'agNumberColumnFilter',
        filterParams: undefined,
        order: 19,
        sort: null,
        sortable: true,
        title: 'rules.threshold3',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'threshold3Description',
        filter: undefined,
        filterParams: undefined,
        order: 20,
        sort: null,
        sortable: false,
        title: 'rules.threshold3Description',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'startDate',
        filter: 'agDateColumnFilter',
        filterParams: {
          comparator: expect.any(Function),
        },
        order: 21,
        sort: null,
        sortable: true,
        title: 'rules.startDate',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'execDay',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 22,
        sort: null,
        sortable: true,
        title: 'rules.execDay',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'execInterval',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 23,
        sort: null,
        sortable: true,
        title: 'rules.execInterval',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'endDate',
        filter: 'agDateColumnFilter',
        filterParams: {
          comparator: expect.any(Function),
        },
        order: 24,
        sort: null,
        sortable: true,
        title: 'rules.endDate',
        valueFormatter: expect.any(Function),
        visible: true,
      },
      {
        alwaysVisible: true,
        cellRenderer: expect.any(Function),
        colId: 'deactivated',
        filter: 'agSetColumnFilter',
        filterParams: {
          valueFormatter: expect.any(Function),
          values: [true, false],
        },
        order: 25,
        sort: null,
        sortable: true,
        title: 'rules.deactivated',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'activeCount',
        filter: 'agNumberColumnFilter',
        filterParams: undefined,
        order: 26,
        sort: null,
        sortable: true,
        title: 'rules.activeCount',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'inactiveCount',
        filter: 'agNumberColumnFilter',
        filterParams: undefined,
        order: 27,
        sort: null,
        sortable: true,
        title: 'rules.inactiveCount',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'completedCount',
        filter: 'agNumberColumnFilter',
        filterParams: undefined,
        order: 28,
        sort: null,
        sortable: true,
        title: 'rules.completedCount',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'usernameCreated',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 29,
        sort: null,
        sortable: true,
        title: 'alert_rules.table.column.usernameCreated',
        visible: true,
      },
      {
        alwaysVisible: false,
        cellRenderer: undefined,
        colId: 'usernameLastChanged',
        filter: 'agTextColumnFilter',
        filterParams: undefined,
        order: 30,
        sort: null,
        sortable: true,
        title: 'alert_rules.table.column.usernameLastChanged',
        visible: true,
      },
    ]);
  });
});
