export enum TitleId {
  STRING_OUTP_INPUT = 'STRING_OUTP_INPUT',
  STRING_OUTP_RESULTS = 'STRING_OUTP_RESULTS',
  STRING_OUTP_RESULTS_FOR_GREASE_SELECTION = 'STRING_OUTP_RESULTS_FOR_GREASE_SELECTION',
  STRING_OUTP_RESULTS_FOR_GREASE_SERVICE_STRING_OUTP_GREASE_QUANTITY_IN_CCM = 'STRING_OUTP_RESULTS_FOR_GREASE_SERVICE_STRING_OUTP_GREASE_QUANTITY_IN_CCM',
  STRING_OUTP_OVERVIEW_OF_CALCULATION_DATA_FOR_GREASES = 'STRING_OUTP_OVERVIEW_OF_CALCULATION_DATA_FOR_GREASES',
}

export enum Hint {
  ERRORS = 'Errors',
  WARNINGS = 'Warnings',
  NOTES = 'Notes',
}

export enum Field {
  GREASE_GRADE = 'Grease grade',
  BASEOIL = 'BaseOil',
  NLGI = 'NLGI',
  THICKENER = 'Thickener',
  QVIN = 'Qvin',
}
