export const COMPARE_ITEMS_MIN_COUNT = 2;
export const COMPARE_ITEMS_MAX_COUNT = 2;
export const PORTFOLIO_ANALYSIS_ITEMS_MIN_COUNT = 2;
export const PORTFOLIO_ANALYSIS_ITEMS_MAX_COUNT = 25;
export const BOM_EXPORT_MIN_COUNT = 1;
export const BOM_EXPORT_MAX_COUNT = 30;
export const BOM_EXPORT_LOADING_TIMEOUT = 2000;
