import { Alert, AlertCategory, OpenFunction } from './model';

export const mockAlertResult: Alert[] = [
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '1',
    customerName: 'first customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.ACIADP,
  },
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '1',
    customerName: 'first customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.NPOSDP,
  },
  {
    open: false,
    priority: false,
    alertPriority: 2,
    deactivated: false,
    customerNumber: '2',
    customerName: 'second customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.CFSUAO,
  },
];

export const largeMockAlertResult: Alert[] = [
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '1',
    customerName: 'first customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.ACIADP,
  },
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '1',
    customerName: 'first customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.NPOSDP,
  },
  {
    open: false,
    priority: false,
    alertPriority: 2,
    deactivated: false,
    customerNumber: '2',
    customerName: 'second customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.CFSUAO,
  },
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '3',
    customerName: 'third customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.CFSUAO,
  },
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '3',
    customerName: 'third customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.CFSUAO,
  },
  {
    open: false,
    priority: false,
    alertPriority: 1,
    deactivated: false,
    customerNumber: '3',
    customerName: 'third customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.CFSUAO,
  },
  {
    open: false,
    priority: false,
    alertPriority: 2,
    deactivated: false,
    customerNumber: '3',
    customerName: 'third customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.NPOSDP,
  },
  {
    open: false,
    priority: false,
    alertPriority: 3,
    deactivated: false,
    customerNumber: '3',
    customerName: 'third customer',
    openFunction: OpenFunction.Validation_Of_Demand,
    type: AlertCategory.ACIADP,
  },
];
