import { OverviewCard } from '../../../shared/components/overview-card/overview-card.model';

export const applications: OverviewCard[] = [
  {
    image: '../../../assets/img/app-preview/matgpt.png',
    icon: '../../../assets/img/matgpt.svg',
    title: 'MaterialsGPT Prototype',
    description:
      'Join the testing phase for the MaterialsGPT prototype and share feedback',
    link: 'mailto:soniash@schaeffler.com?subject=Request%20Access%20to%20MaterialsGPT%20Prototype&cc=krausrbe@schaeffler.com&body=Dear%20MaterialsGPT-Team%2C%0A%0AI%20would%20like%20to%20request%20access%20to%20the%20MaterialsGPT%20prototype%20to%20provide%20feedback%20during%20the%20application%20development.%20%0A%0ABest%20regards',
    learnMoreLink: '/learn-more/materials-gpt',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'applications.materialsGPT',
    highlighted: true,
  },
  {
    image: '../../../assets/img/app-preview/hc.jpg',
    icon: '../../../assets/img/hardness_converter.svg',
    title: 'Hardness Converter',
    description: 'Convert hardness and tensile-strength values',
    link: 'https://hardness-converter.com',
    learnMoreLink: 'https://hardness-converter.com/learn-more',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'applications.hardnessConverter',
  },
  {
    image: '../../../assets/img/app-preview/msd.jpg',
    icon: '../../../assets/img/Materials_Supplier_Database.svg',
    title: 'Materials Supplier Database',
    description: 'Find released materials suppliers and their CO₂ footprints',
    link: '/materials-supplier-database',
    learnMoreLink: '/learn-more/materials-supplier-database',
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    requiredRoles: ['material-supplier-database-read-user'],
    requestAccessLink: 'how-to-get-access',
    inverted: true,
    translationKey: 'applications.materialsSupplierDatabase',
  },
  {
    image: '../../../assets/img/app-preview/aqm.jpg',
    icon: '../../../assets/img/aqm_calculator.svg',
    title: 'AQM Calculator',
    description: 'Calculate analytical QM value and sum value',
    link: '/aqm-calculator',
    learnMoreLink: '/learn-more/aqm-calculator',
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'applications.aqmCalculator',
  },
  {
    image: '../../../assets/img/app-preview/ga.png',
    icon: '../../../assets/img/greaseapp.svg',
    title: 'Grease App',
    description: 'Calculate the optimum amount of lubricant for your bearing',
    link: 'https://greaseapp.dp.schaeffler',
    learnMoreLink: 'https://medias.schaeffler.de/en/faq/grease-app',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'applications.greaseApp',
  },
  {
    image: '',
    icon: '../../../assets/img/insulation_solutions.svg',
    title: 'Insulation Solutions',
    description: 'Find the right insulation product for your application',
    link: '/learn-more/insulation-solutions',
    learnMoreLink: '/learn-more/insulation-solutions',
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'applications.insulation-solutions',
  },
  {
    image: '',
    icon: '../../../assets/img/matp.svg',
    title: 'Material Properties Estimator',
    description:
      'Estimate static and cyclic materials properties according to S 130999',
    link: 'https://matlab-web-app:9988/webapps/home/login.html?afterlogin=%2Fwebapps%2Fhome%2Fsession.html%3Fapp%3DSchaeffler%252FMaterialparameterestimation',
    learnMoreLink: '/learn-more/material-properties-estimator',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'applications.matp',
  },
  {
    image: '',
    icon: '../../../assets/img/specviewer.svg',
    title: 'SpecViewer',
    description: 'Overview of materials-related group standards',
    link: 'https://confluence.schaeffler.com/display/SpecViewer/',
    learnMoreLink: undefined,
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'applications.specviewer',
  },
  {
    image: '',
    icon: '../../../assets/img/wiam.svg',
    title: 'WIAM Material Database',
    description: 'Find properties of specified materials',
    link: 'https://wiamp.schaeffler.com:8443/rdc/raw',
    learnMoreLink:
      'https://worksite.sharepoint.com/sites/Central-Technologies/SitePages/WIAM.aspx?csf=1&web=1&e=0ihPGt&xsdata=MDV8MDJ8a3JhdXNyYmVAc2NoYWVmZmxlci5jb218MmZiY2Q2NDI0OTQ4NDMwYzYwYTMwOGRjZjFkODg4YWN8Njc0MTY2MDQ2NTA5NDAxNDk4NTk0NWU3MDlmNTNkM2Z8MXwwfDYzODY1MTE1OTUyMTIxMzczNHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MHx8fA%3d%3d&sdata=c0tkWG1XSEpRRml5aXF6N1hnQmczKzNsK1M3TGg3QmJNeXFCbWx3L0dUZz0%3d',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'applications.wiam',
  },
  {
    image: '',
    icon: '../../../assets/img/carbonitriding_prediction.svg',
    title: 'Carbonitriding Prediction',
    description: 'Predict carbonitriding profiles based on furnace parameters',
    link: 'https://matlab-web-app:9988/webapps/home/session.html?app=Schaeffler%2FCarbonitriding_Prediction_Tool',
    learnMoreLink:
      'https://worksite.sharepoint.com/sites/Central-Technologies/SitePages/Simulation-Tool-for-Carbonitriding-Heat-Treatment.aspx',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'applications.carbonitridingPrediction',
  },
  {
    image: '',
    icon: '../../../assets/img/polyassist.svg',
    title: 'Polyassist',
    description: 'Perform a strength assessment for fiber reinforced polymers',
    link: 'https://worksite.sharepoint.com/sites/Central-Technologies/SitePages/PolyAssist.aspx',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'applications.polyassist',
  },
  {
    image: '',
    icon: '../../assets/img/suma.svg',
    title: 'Sustainability Manager',
    description: 'Creation of decarbonization scenarios & roadmaps',
    link: 'https://suma.sps.schaeffler/',
    learnMoreLink:
      'https://confluence.schaeffler.com/pages/viewpage.action?pageId=259047258',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
  },
  {
    image: '',
    icon: '../../../assets/img/substance_information_system.svg',
    title: 'Substance Information System',
    description: 'Information about substances used and released at Schaeffler',
    link: 'https://ws006046:8401/OeffentlicherBereich/Stoffsuche/OeffentlicheSuche.aspx?ReturnUrl=/',
    learnMoreLink: '/learn-more/substance-information-system',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: false,
    inverted: true,
  },
  {
    image: '',
    icon: '../../assets/img/cct.svg',
    title: 'CCT-Calculator ',
    description:
      'Calculate phase transformations for through-hardening bearing steels',
    link: 'https://matlab-web-app:9988/webapps/home/session.html?app=Schaeffler%2FCCTCalculator',
    learnMoreLink: '/learn-more/continous-cooling-transformation',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: false,
    inverted: true,
  },
];
