import { OverviewCard } from '../../../shared/components/overview-card/overview-card.model';

export const integratedApps: OverviewCard[] = [
  {
    image: '../../../assets/img/app-preview/hc.jpg',
    icon: '../../../assets/img/hardness_converter.svg',
    title: 'Hardness Converter',
    description: 'Convert hardness and tensile-strength values',
    link: '/hardness-converter',
    learnMoreLink: '/learn-more/hardness-converter',
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'internalApplications.hardnessConverter',
  },
  {
    image: '../../../assets/img/app-preview/msd.jpg',
    icon: '../../../assets/img/Materials_Supplier_Database.svg',
    title: 'Materials Supplier Database',
    description: 'Find released materials suppliers and their CO₂ footprints',
    link: '/materials-supplier-database',
    learnMoreLink: undefined,
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    requiredRoles: ['material-supplier-database-read-user'],
    inverted: true,
    translationKey: 'internalApplications.materialsSupplierDatabase',
  },
  {
    image: '../../../assets/img/app-preview/aqm.jpg',
    icon: '../../../assets/img/aqm_calculator.svg',
    title: 'AQM Calculator',
    description: 'Calculate analytical QM value and sum value',
    link: '/aqm-calculator',
    learnMoreLink: undefined,
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'internalApplications.aqmCalculator',
  },
  {
    image: '../../../assets/img/app-preview/ltp.jpg',
    icon: '../../../assets/img/lifetime_predictor.svg',
    title: 'Lifetime Predictor',
    description:
      'Predict the conventional fatigue lifetime of metallic components',
    link: '/lifetime-predictor',
    learnMoreLink: undefined,
    disableImageHoverEffect: false,
    external: false,
    learnMoreExternal: false,
    requiredRoles: ['lifetime-predictor-user'],
    inverted: true,
    translationKey: 'internalApplications.lifetimePredictor',
  },
  {
    image: '../../../assets/img/app-preview/ga.png',
    icon: '../../../assets/img/greaseapp.svg',
    title: 'Grease App',
    description: 'Calculate the optimum amount of lubricant for your bearing',
    link: 'https://greaseapp.dp.schaeffler',
    learnMoreLink: undefined,
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'internalApplications.greaseApp',
  },
];
