import { OverviewCard } from '../../../shared/components/overview-card/overview-card.model';

export const linkedApps: OverviewCard[] = [
  {
    image: '',
    icon: '../../../assets/img/matp.svg',
    title: 'Material Properties Estimator',
    description:
      'Estimate static and cyclic materials properties according to S 130999',
    link: 'https://matlab-web-app:9988/webapps/home/login.html?afterlogin=%2Fwebapps%2Fhome%2Fsession.html%3Fapp%3DSchaeffler%252FMaterialparameterestimation',
    learnMoreLink: '/learn-more/material-properties-estimator',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: false,
    inverted: true,
    translationKey: 'linkedApplications.matp',
  },
  {
    image: '',
    icon: '../../../assets/img/specviewer.svg',
    title: 'SpecViewer',
    description: 'Overview of materials-related group standards',
    link: 'https://confluence.schaeffler.com/display/SpecViewer/',
    learnMoreLink: undefined,
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'linkedApplications.specviewer',
  },
  {
    image: '',
    icon: '../../../assets/img/wiam.svg',
    title: 'WIAM Material Database',
    description: 'Find properties of specified materials',
    link: 'https://wiamp.schaeffler.com:8443/rdc/raw',
    learnMoreLink:
      'https://worksite.sharepoint.com/sites/Central-Technologies/SitePages/WIAM.aspx?csf=1&web=1&e=0ihPGt&xsdata=MDV8MDJ8a3JhdXNyYmVAc2NoYWVmZmxlci5jb218MmZiY2Q2NDI0OTQ4NDMwYzYwYTMwOGRjZjFkODg4YWN8Njc0MTY2MDQ2NTA5NDAxNDk4NTk0NWU3MDlmNTNkM2Z8MXwwfDYzODY1MTE1OTUyMTIxMzczNHxVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MHx8fA%3d%3d&sdata=c0tkWG1XSEpRRml5aXF6N1hnQmczKzNsK1M3TGg3QmJNeXFCbWx3L0dUZz0%3d',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'linkedApplications.wiam',
  },
  {
    image: '',
    icon: '../../../assets/img/carbonitriding_prediction.svg',
    title: 'Carbonitriding Prediction',
    description: 'Predict carbonitriding profiles based on furnace parameters',
    link: 'https://matlab-web-app:9988/webapps/home/session.html?app=Schaeffler%2FCarbonitriding_Prediction_Tool',
    learnMoreLink:
      'https://worksite.sharepoint.com/sites/Central-Technologies/SitePages/Simulation-Tool-for-Carbonitriding-Heat-Treatment.aspx',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'linkedApplications.carbonitridingPrediction',
  },
  {
    image: '',
    icon: '../../../assets/img/polyassist.svg',
    title: 'Polyassist',
    description: 'Perform a strength assessment for fiber reinforced polymers',
    link: 'https://worksite.sharepoint.com/sites/Central-Technologies/SitePages/PolyAssist.aspx',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
    translationKey: 'linkedApplications.polyassist',
  },
  {
    image: '',
    icon: '../../assets/img/suma.svg',
    title: 'Sustainability Manager',
    description: 'Creation of decarbonization scenarios & roadmaps',
    link: 'https://suma.sps.schaeffler/',
    learnMoreLink:
      'https://confluence.schaeffler.com/pages/viewpage.action?pageId=259047258',
    disableImageHoverEffect: false,
    external: true,
    learnMoreExternal: true,
    inverted: true,
  },
];
