export enum UserRoles {
  BASIC = 'BASIC',
  MANUAL_PRICE = 'PRICE.MANUAL',
  COST_GPC = 'COST.GPC',
  COST_SQV = 'COST.SQV',
  REGION_WORLD = 'REGION.WORLD',
  SECTOR_ALL = 'SECTOR.ALL',
  REGION_PREFIX = 'REGION.',
  SECTOR_PREFIX = 'SECTOR.',
  COST_PREFIX = 'COST.',
}
