import { Control, Type, Unit } from '../models';

export const LOAD_ASSESSMENT_CONTROLS: Control[] = [
  {
    label: 'centerLoadFx',
    formControl: 'centerLoadFx',
    unit: Unit.load,
    type: Type.centerload,
    color: '#FF5627',
  },
  {
    label: 'centerLoadFy',
    formControl: 'centerLoadFy',
    unit: Unit.load,
    type: Type.centerload,
    color: '#FF9300',
  },
  {
    label: 'centerLoadFz',
    formControl: 'centerLoadFz',
    unit: Unit.load,
    type: Type.centerload,
    color: '#E8497F',
  },
  {
    label: 'centerLoadMy',
    formControl: 'centerLoadMy',
    unit: Unit.loadMomentum,
    type: Type.centerload,
    color: '#DF3A72',
  },
  {
    label: 'centerLoadMz',
    formControl: 'centerLoadMz',
    unit: Unit.loadMomentum,
    type: Type.centerload,
    color: '#805E54',
  },
  {
    label: 'lsp01Strain',
    formControl: 'lsp01Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#0e656d',
  },
  {
    label: 'lsp03Strain',
    formControl: 'lsp03Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#188899',
  },
  {
    label: 'lsp05Strain',
    formControl: 'lsp05Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#1d9cb2',
  },
  {
    label: 'lsp07Strain',
    formControl: 'lsp07Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#24b1cd',
  },
  {
    label: 'lsp09Strain',
    formControl: 'lsp09Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#28c1e0',
  },
  {
    label: 'lsp11Strain',
    formControl: 'lsp11Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#37cae6',
  },
  {
    label: 'lsp13Strain',
    formControl: 'lsp13Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#56d4ec',
  },
  {
    label: 'lsp15Strain',
    formControl: 'lsp15Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#85e1f3',
  },
  {
    label: 'lsp02Strain',
    formControl: 'lsp02Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#0d4b30',
  },
  {
    label: 'lsp04Strain',
    formControl: 'lsp04Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#166649',
  },
  {
    label: 'lsp06Strain',
    formControl: 'lsp06Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#1c7656',
  },
  {
    label: 'lsp08Strain',
    formControl: 'lsp08Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#218664',
  },
  {
    label: 'lsp10Strain',
    formControl: 'lsp10Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#259370',
  },
  {
    label: 'lsp12Strain',
    formControl: 'lsp12Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#37a482',
  },
  {
    label: 'lsp14Strain',
    formControl: 'lsp14Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#56b496',
  },
  {
    label: 'lsp16Strain',
    formControl: 'lsp16Strain',
    unit: Unit.load,
    type: Type.load,
    color: '#84cab3',
  },
];
