export const darkGrey = '#c0c0c0';
export const dimmedRed = '#A31839';
export const dimmedBlue = '#A4CADE';
export const dimmedYellow = '#E3D07D';
export const dimmedGrey = '#646464';
export const dimmedGreen = '#7EA69B';
export const dimmedPurple = '#A4ACDE';
export const disabledGrey = '#00000042';

export const schaefflerColor = '#00893D';
export const demandValidationPartialWeekColor = '#EBEEF0';
export const demandValidationNotEditableColor = '#EBEEF0';
export const demandValidationEditableColor = '#CCE8D9';
export const demandValidationToSmallColor = '#FDE7A3';
export const demandValidationWrongInputColor = '#DFADB9';
export const demandValidationInFixZoneColor = '#EBEEF0';
export const borderColor = '#00000052'; // #000000 with 32% opacity
export const textDarkGrey = '#000000DE'; // #000000 with 87% opacity
export const errorColor = '#A31839';
export const errorColorLight = '#F7D4D4';
export const transparent = 'transparent';
