export enum ApprovalEventType {
  STARTED = 'STARTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FORWARDED = 'FORWARDED',
  CANCELLED = 'CANCELLED',
  AUTO_APPROVAL = 'AUTO_APPROVAL',
}
