import { QuickFilter } from '@mac/feature/materials-supplier-database/models';
import {
  CASTING_DIAMETER,
  CASTING_MODE,
  LAST_MODIFIED,
  MANUFACTURER_SUPPLIER_NAME,
  MANUFACTURER_SUPPLIER_PLANT,
  MATERIAL_STANDARD_MATERIAL_NAME,
  MATERIAL_STANDARD_STANDARD_DOCUMENT,
  MAX_DIMENSION,
  PRODUCT_CATEGORY,
  RATING,
  RELEASE_RESTRICTIONS,
  STATUS,
} from '@mac/msd/constants';

export const CERAMIC_STATIC_QUICKFILTERS: QuickFilter[] = [
  {
    title: 'default',
    filter: {},
    columns: [
      MATERIAL_STANDARD_MATERIAL_NAME,
      MATERIAL_STANDARD_STANDARD_DOCUMENT,
      MANUFACTURER_SUPPLIER_NAME,
      MANUFACTURER_SUPPLIER_PLANT,
      CASTING_MODE,
      CASTING_DIAMETER,
      MAX_DIMENSION,
      RATING,
      RELEASE_RESTRICTIONS,
      PRODUCT_CATEGORY,
      STATUS,
      LAST_MODIFIED,
    ],
    custom: false,
  },
];
